### PR TITLE
feat: add examples how to call dextra quote

### PR DESCRIPTION
**Pull request by RafilxTenfen**

### CODE REVIEW

**Review by Vadymykh — CHANGES_REQUESTED** [review]
- let's move types into separate folder src/types. EVM and Solana into separate files
- I don't think we need `ReplaceHexWithString` type. Just replace `0x${string}` type tostring everywhere in example repo
- Let's remove ExtraData types by just moving insides into parent type (EvmEstimation)
- Chain IDs should be in separate file as well
- let's move API keys, DextraQuoteURL and everything else into .env file. We dn't want those in public repo. If this is an active API key, lets clear it from repo so it wouldn't be visible even in history
- let's create separate file for each example in src/examples folder and name those files accordingly
- let's create ethers provider and wallet and show how to actually sign these transactions
- before each EVM transaction let's make sure token IN has enough allowance and approve it if it's doesn't. Contact me for more explanations
- let's start with approving a single transaction example and then do the rest
- let's define all constants like srcToken, destToken, amount at the very start of the `main` function and then just pas those
- `amount`, `bridgeExtraNative`, `gasRefuel` and other amounts should be strings. Javascript sometimes becomes weird with weird numbers and it can send something like `amount=1e+24` to backend, which we don't want
- instead of having url += for each params use axios params. ALL params should be set that way. Contact me for more explanations.


This should be enough for the start. Contact me with any questions

**Comment by RafilxTenfen** [comment]
> let's move API keys, DextraQuoteURL and everything else into .env file. We dn't want those in public repo. If this is an active API key, lets clear it from repo so it wouldn't be visible even in history

I have deleted the API key exposed

> let's define all constants like srcToken, destToken, amount at the very start of the main function and then just pas those

Done 

@Vadymykh already made most of the changes, what is missing is the execution of the fetch quotes file, which I think it is okay just to have examples of the [fetch quote](https://github.com/shogun-network/examples/blob/2ba55110a604b20969559ef990cbc145f9c1b467/src/examples/fetchQuote.ts#L9) 

In my mind, we would only show the examples of building queries, but adding the execution with the wallet was a great addition, what do you guys think?

**Comment by Vadymykh** [comment]
I'll add executing Solana transactions examples as well. I don't think fetching quotes without knowing how to execute them is something people want but having more quote examples is a good thing

**Review by Vadymykh — APPROVED** [review]
Added Solana swap and bridge transactions execution

**Pull request merged**
